name = "LeanUtils"
version = "0.1.0"
defaultTargets = ["KernelCheck", "ExtractSorry", "LeanUtils"]
testDriver = "LeanUtilsTest"

[[lean_lib]]
name = "LeanUtils"

[[lean_lib]]
name = "LeanUtilsTest"
root = "LeanUtilsTest"

[[lean_lib]]
name = "bins"

[[lean_exe]]
name = "KernelCheck"
root = "bins.KernelCheck"

[[lean_exe]]
name = "ExtractSorry"
root = "bins.ExtractSorry"
